[default]
src = 'contracts'
out = 'out'
libs = ['lib']

remappings =  [
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
[hardhat]
src = "contracts"
test = "test"

# See more config options https://github.com/gakonst/foundry/tree/master/config