[default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin/=node_modules/@openzeppelin/contracts/']

# See more config options https://github.com/gakonst/foundry/tree/master/config