name: Actions
on:
    push

env:
  ## Sets environment variable
  RPC_URL: ${{secrets.RPC_URL}}
  PK: ${{secrets.PK}}
  ETHERSCAN_API: ${{secrets.ETHERSCAN_API}} 

jobs:
    build:
        name: Run build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install

            - name: Install submodules
              run: git submodule update --init --recursive

            - name: Compile contracts
              run: yarn build

    lint:
        name: Run lints
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install

            - name: Run Prettier
              run: yarn run lint

    test:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: yarn install
              
            - name: Install submodules
              run: git submodule update --init --recursive

            - name: Compile contracts
              run: yarn build
            
            - name: Test contracts
              run: yarn test